[build]
  command = "pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Subdomain = ["app"]}

[context.production]
  environment = { NODE_VERSION = "20" }
  